<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>BarberiaTurnos</AssemblyName>
    <RootNamespace>BarberiaTurnos</RootNamespace>
  </PropertyGroup>
</Project>
